export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_PRODUCTS_ON_HAND = "GET_PRODUCTS_ON_HAND";
export const GET_PRODUCTS_ON_HAND_VARIATIONS = "GET_PRODUCTS_ON_HAND_VARIATIONS";
export const GET_PRODUCT_TRANSFER_VIEW = "GET_PRODUCT_TRANSFER_VIEW";
export const GET_PRODUCT_TRANSFER_HISTORY = "GET_PRODUCT_TRANSFER_HISTORY";
export const GET_PRODUCT_TRANSFER_HISTORY_DETAILS = "GET_PRODUCT_TRANSFER_HISTORY_DETAILS";
export const CREATE_PRODUCT_TRANSFER = "CREATE_PRODUCT_TRANSFER";
export const GET_PURCHASE_INVOICE_LIST = "GET_PURCHASE_INVOICE_LIST";
export const GET_LAST_TRANSACTION = "GET_LAST_TRANSACTION";
export const GET_PRODUCT_BY_PURCHASE_INVOICE = "GET_PRODUCT_BY_PURCHASE_INVOICE";
export const GET_PRODUCT_BY_LAST_TRANSACTION = "GET_PRODUCT_BY_LAST_TRANSACTION";
export const GET_PRODUCT_BY_IMEI_SCAN = "GET_PRODUCT_BY_IMEI_SCAN";

