export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_SKU_TRANSFER_VIEW_DATA = "GET_SKU_TRANSFER_VIEW_DATA";
export const GET_SKU_TRANSFER_STORE_DATA = "GET_SKU_TRANSFER_STORE_DATA";
export const SKU_TRANSFER = "SKU_TRANSFER";
export const SKU_TRANSFER_HISTORY = "SKU_TRANSFER_HISTORY";
export const SKU_TRANSFER_HISTORY_DETAILS = "SKU_TRANSFER_HISTORY_DETAILS";