export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_TRANSACTION_RECORDS = "GET_TRANSACTION_RECORDS";
export const GET_CASH_IN_RECORDS = "GET_CASH_IN_RECORDS";
export const GET_CASH_OUT_RECORDS = "GET_CASH_OUT_RECORDS";
export const GET_VERIFICATION_RECORD = "GET_VERIFICATION_RECORD";
export const GET_USER_LOG = "GET_USER_LOG";