export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_PRODUCT_MODEL_LIST = "GET_PRODUCT_MODEL_LIST";
export const CREATE_PRODUCT_MODEL = "CREATE_PRODUCT_MODEL";