export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_BRAND_LIST = "GET_BRAND_LIST";
export const CREATE_BRAND = "CREATE_BRAND";