export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_PURCHASE_VARIATION = "GET_PURCHASE_VARIATION";
export const GET_STORE_PURCHASE_VARIATION_VIEW = "GET_STORE_PURCHASE_VARIATION_VIEW";  
export const GET_PURCHASE_VARIATIONS_BY_ID = "GET_PURCHASE_VARIATIONS_BY_ID";
export const CREATE_PURCHASE_VARIATIONS = "CREATE_PURCHASE_VARIATIONS"

