export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";  
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

export const GET_PURCHASE = "GET_PURCHASE";
export const CREATE_PURCHASE = "CREATE_PURCHASE";
export const GET_STORE_PURCHASE_VIEW = "GET_STORE_PURCHASE_VIEW";
export const GET_PURCHASE_INVOICE = "GET_PURCHASE_INVOICE";
export const PURCHASE_TOGGLE_LOCK = "PURCHASE_TOGGLE_LOCK";
export const PURCHASE_VERIFICATION = "PURCHASE_VERIFICATION";
export const GET_PURCHASE_RETURN_LIST = "GET_PURCHASE_RETURN_LIST";
export const GET_PURCHASE_RETURN_VARIATIONS = "GET_PURCHASE_RETURN_VARIATIONS";
export const PURCHASE_RETURN_VERIFICATION = "PURCHASE_RETURN_VERIFICATION";
export const CREATE_PURCHASE_RETURN = "CREATE_PURCHASE_RETURN";

