export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";  
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

export const GET_PURCHASE = "GET_PURCHASE";
export const CREATE_PURCHASE = "CREATE_PURCHASE";
export const GET_STORE_PURCHASE_VIEW = "GET_STORE_PURCHASE_VIEW";

