export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_COMMISSION_BY_SALE_INVOICE_FP = "GET_COMMISSION_BY_SALE_INVOICE_FP";
export const GET_COMMISSION_BY_CUSTOMER = "GET_COMMISSION_BY_CUSTOMER";
export const GET_SALES_DUE_FP = "GET_SALES_DUE_FP";
export const GET_COMISSION_BY_RETURN_INVOICE_FP = "GET_COMISSION_BY_RETURN_INVOICE_FP";
