// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_ROLE = "GET_ROLE";
export const CREATE_ROLE = "CREATE_ROLE";
export const GET_PERMISSION = "GET_PERMISSION";
export const ASSIGN_PERMISSION = "ASSIGN_PERMISSION";
export const GET_ROLE_PERMISSION_SELECT = "GET_ROLE_PERMISSION_SELECT";
