export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";    
export const GET_AVERAGE_PURCHASE_PRICES = "GET_AVERAGE_PURCHASE_PRICE";
export const GET_PURCHASE_PRODUCT_LIST = "GET_PURCHASE_PRODUCT_LIST";
