export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
export const GET_POOL_HISTORY = "GET_POOL_HISTORY";
export const DELETE_POOL_HISTORY = "DELETE_POOL_HISTORY";
export const UPDATE_POOL_HISTORY = "UPDATE_POOL_HISTORY";
export const ADD_POOL = "ADD_POOL";
export const WITHDRAW_POOL = "WITHDRAW_POOL";
